name:                cfdbadminton
version:             0.1.0
github:              "marcingol1/cfdbadminton"
license:             BSD3
author:              "Marcin Gol"
maintainer:          "golmarcin@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/marcingol1/cfdbadminton#readme>

dependencies:
- base >= 4.7 && < 5
- serverless-haskell
- aeson

library:
  source-dirs: src

executables:
  cfdbadminton-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cfdbadminton

tests:
  cfdbadminton-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cfdbadminton
